### ISSUE TITLE
Yeni Arayüz Önerisi

### ISSUE THREAD

**Issue by hmert** [naynco/nayn.org#6]
https://codepen.io/hmert/pen/wvKVyWb
![image](https://user-images.githubusercontent.com/182906/83336548-126eee80-a2bd-11ea-8c62-f1d6c957e865.png)

@keremalan senin yaptığın arayüzü baz alarak bunu yaptım. Eğer sen de beğenirsen güncelleyebiliriz.

**Comment by keremalan** [comment]
@hmert gayet güzel olmuş. Font-awesome'da bir sorun yaşadığım için icon ekleyememiştim. _Font-awesome ile eklersek daha güzel olur._

Şimdi kodu inceledim. Zaten font-awesome kullanılmış :)

**Comment by keremalan** [comment]
@hmert renkleri değiştirmek yerine benim gönderdiğim renkleri kullanmak daha mantıklı. Icon eklenmesi konusunda değişiklikler hoşuma gitmişti ama renk göz yorucu.

**Comment by hmert** [comment]
Pull request yolla o zaman :)

**Comment by keremalan** [comment]
`:root {
  --primaryColor: #ffffff;
  --secondaryColor: #f2f2f2;
  --thirdColor: #2d2d2d;
  --textColor: #626569; 
}

body,
html {
  height: 100%;
  width: 100%;
  margin: 0;
  padding: 0;
  background: var(--primaryColor) !important;
}

button {
  border: none;
}

.searchbar {
  margin-bottom: auto;
  margin-top: auto;
  height: 60px;
  background-color: var(--secondaryColor);
  border-radius: 30px;
  padding: 10px;
}

.search_input {
  color: var(--thirdColor);
  border: 0;
  outline: 0;
  background: none;
  padding: 0 10px;
  width: 300px;
  caret-color: var(--textColor);
  line-height: 40px;
  transition: width 0.4s linear;
}

.searchbar:hover > .search_icon {
  background: white;
  color: var(--thirdColor);
}

.search_icon {
  height: 40px;
  width: 40px;
  float: right;
  display: flex;
  justify-content: center;
  align-items: center;
  border-radius: 50%;
  color: var(--thirdColor);
  text-decoration: none;
  background:transparent;
}

  footer {
    height: 60px;
    line-height:60px;
    text-align:center;
    background-color: var(--secondaryColor);
    position: absolute;
    bottom: 0;
    width: 100%;
  }

  footer > div {
    display: inline-flex;
  }

  footer > div > ul > li{
    list-style-type: none;
    
    margin-right: 2vh;
  }
`
