### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by keremalan** [naynco/nayn.org#8]
Dark modu açmak için gereken tasarımı yapmıştım ama doğru yöntemi bulamadığım için ekleyemedim. Buttonu ekleyebilirsek kullanabiliriz.

https://www.figma.com/file/KYowORljfswEFv8bEoioym/nayn.search?node-id=0%3A1

Pages > Screens

**Comment by hmert** [comment]
@keremalan iyi fikir, buna da bakayım.

**Comment by keremalan** [comment]
Geçiş eklenmemiş sanırım ve en alttaki yazı okunmuyor.

**Comment by hmert** [comment]
@keremalan slider yapacağım vaktim olduğunda :)

**Comment by keremalan** [comment]
Ben yazayım bu gece onu da yarın ekleriz @hmert
